# Generated by Django 4.2.1 on 2023-05-12 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='second_image',
            field=models.CharField(blank=True, max_length=9999),
        ),
    ]
